package pe.edu.upeu.casaonada.orden.domain;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.OffsetDateTime; import java.util.*;
@Entity @Table(name="ordenes") public class Orden {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="cliente_id",nullable=false) private Long clienteId; @Column(name="reserva_id") private Long reservaId; @Enumerated(EnumType.STRING) @Column(name="tipo_operacion",nullable=false,length=20) private TipoOperacion tipoOperacion; @Column(nullable=false,length=8) private String moneda; @Column(nullable=false,precision=14,scale=2) private BigDecimal subtotal; @Column(nullable=false,precision=14,scale=2) private BigDecimal total; @Column(name="monto_adelanto",nullable=false,precision=14,scale=2) private BigDecimal montoAdelanto; @Enumerated(EnumType.STRING) @Column(nullable=false,length=30) private EstadoOrden estado; @Column(name="created_at",nullable=false,updatable=false) private OffsetDateTime createdAt; @Column(name="updated_at",nullable=false) private OffsetDateTime updatedAt;
 @OneToMany(mappedBy="orden",cascade=CascadeType.ALL,orphanRemoval=true,fetch=FetchType.LAZY) private List<DetalleOrden> detalles=new ArrayList<>();
 @PrePersist void p(){var n=OffsetDateTime.now();createdAt=n;updatedAt=n;} @PreUpdate void u(){updatedAt=OffsetDateTime.now();}
 public void agregarDetalle(DetalleOrden d){d.setOrden(this);detalles.add(d);}
 public Long getId(){return id;} public Long getClienteId(){return clienteId;} public void setClienteId(Long v){clienteId=v;} public Long getReservaId(){return reservaId;} public void setReservaId(Long v){reservaId=v;} public TipoOperacion getTipoOperacion(){return tipoOperacion;} public void setTipoOperacion(TipoOperacion v){tipoOperacion=v;} public String getMoneda(){return moneda;} public void setMoneda(String v){moneda=v;} public BigDecimal getSubtotal(){return subtotal;} public void setSubtotal(BigDecimal v){subtotal=v;} public BigDecimal getTotal(){return total;} public void setTotal(BigDecimal v){total=v;} public BigDecimal getMontoAdelanto(){return montoAdelanto;} public void setMontoAdelanto(BigDecimal v){montoAdelanto=v;} public EstadoOrden getEstado(){return estado;} public void setEstado(EstadoOrden v){estado=v;} public List<DetalleOrden> getDetalles(){return detalles;} public OffsetDateTime getCreatedAt(){return createdAt;} public OffsetDateTime getUpdatedAt(){return updatedAt;}
}
