server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${PROYECTO_DB_HOST:localhost}:${PROYECTO_DB_PORT:3313}/${PROYECTO_DB_NAME:db_nevoa_proyecto}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${PROYECTO_DB_USERNAME:root}
    password: ${PROYECTO_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:7081/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
